# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1ed5bd23754c1941ad5b62d7eac998a84e2bbb9592a7ae45096a7427e69b1987afe70225ac3f6bda308333acd28f646f2adff74d6c5a4875e95ed37a88cb461

test:
  secret_key_base: c2f902578ebd5fda614151dc73ff42e6c4466e1df680e73e4db155bcf2e717042aa963bb88ae297589730d2f5377c306c775cde8a7d78717d11fb15e6d7b5c56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
